version: '3.8'

services:
  paradedb:
    image: paradedb/paradedb:latest
    container_name: paradedb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - paradedb_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  paradedb_data:
