services:
  elasticsearch-two:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: oio-elasticsearch-two
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=oio-cluster
      - node.name="oio-es--two"
      - network.publish_host=192.168.0.27
      - network.bind_host=0.0.0.0
      - discovery.zen.ping.unicast.hosts=192.168.0.26,192.168.0.27,192.168.0.28
      - node.master=true
      - discovery.zen.minimum_master_nodes=2
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - search.max_buckets=1000
      - indices.breaker.request.limit=40%
      - xpack.license.self_generated.type=basic
    volumes:
      - esdata-two:/usr/share/elasticsearch/data
      - es-logs-two:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

volumes:
  esdata-two:
  es-logs-two: