services:
  elasticsearch-one:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: oio-elasticsearch-one
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=oio-cluster
      - node.name="oio-es-one"
      - network.publish_host=192.168.0.11
      - network.bind_host=0.0.0.0
      - discovery.zen.ping.unicast.hosts=192.168.0.11,192.168.0.27,192.168.0.28
      - node.master=true
      - discovery.zen.minimum_master_nodes=2
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - search.max_buckets=1000
      - indices.breaker.request.limit=40%
    volumes:
      - esdata-one:/usr/share/elasticsearch/data
      - es-logs-one:/usr/share/elasticsearch/logs
      # - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  esdata-one:
  es-logs-one: